title: "Erste Erfahrung im Ausland"
email: denpatin@gmail.com
description: Ein Eindrucksbuch über meine einmonatige Geschäftsreise in Deutschland.
url: "http://dienstreise.dpat.in"
markdown: kramdown
